---
name: BlockReward

author: JaxkDev

version: 1.0.1

api:
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12

main: Jackthehack21\BlockReward\main

commands:
  blockreward:
    description: Use admin tools to configure BlockReward
    permission: reward
    usage: /blockreward help
    aliases:
    - br
    - reward
    
permissions:
    reward:
        default: op
...
